/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTripsRouteImport } from './routes/admin.trips'
import { Route as AdminRoutesRouteImport } from './routes/admin.routes'
import { Route as AdminMonitorRouteImport } from './routes/admin.monitor'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminBusesRouteImport } from './routes/admin.buses'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitorRoute = AdminMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusesRoute = AdminBusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/monitor': typeof AdminMonitorRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/assignments'
    | '/admin/buses'
    | '/admin/drivers'
    | '/admin/monitor'
    | '/admin/routes'
    | '/admin/trips'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/assignments'
    | '/admin/buses'
    | '/admin/drivers'
    | '/admin/monitor'
    | '/admin/routes'
    | '/admin/trips'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/assignments'
    | '/admin/buses'
    | '/admin/drivers'
    | '/admin/monitor'
    | '/admin/routes'
    | '/admin/trips'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitor': {
      id: '/admin/monitor'
      path: '/monitor'
      fullPath: '/admin/monitor'
      preLoaderRoute: typeof AdminMonitorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buses': {
      id: '/admin/buses'
      path: '/buses'
      fullPath: '/admin/buses'
      preLoaderRoute: typeof AdminBusesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminBusesRoute: typeof AdminBusesRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminMonitorRoute: typeof AdminMonitorRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  AdminTripsRoute: typeof AdminTripsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminBusesRoute: AdminBusesRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminMonitorRoute: AdminMonitorRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  AdminTripsRoute: AdminTripsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
